---
language: python
python:
  - 2.7
branches:
  only:
    - master
install:
  - pip install -U pip setuptools tox pytest codecov pytest-cov
  - pip install -r requirements.txt
script:
  - python setup.py pkdeploy
  - py.test --cov=./
after_success:
- codecov

